### ISSUE TITLE
temporary password expired - tried reset, didn't work

### ISSUE THREAD

**Issue by dgraffDana** [bic-boxtech/bic-boxtech.github.io#39]
Using the email rmonti@danacompanies.com tried to log in today with the temporary password.  Prompted that this password has expired.  Selected that forgot the password and sent for a code to reset the password.  No email with the code has been sent to rmonti@danacompanies.com.  Attempted this twice.  I don't see any course to resolve this issue and log in to the account.  Please advise.

**Comment by cmsdroff** [comment]
closing as resolved
