### ISSUE TITLE
Last updated

### ISSUE THREAD

**Issue by rlilov** [bic-boxtech/bic-boxtech.github.io#40]
Hello,
Do you have (looking at payload I can't find it) or plan to have a field that indicates when was the last time when data was updated for a specific container that is returned in the resultset?

**Comment by cmsdroff** [comment]
Hi @rlilov 

Thanks for the question, currently this isn't included at the container record level for Boxtech, we do have this information at the uploader level which logs all uploaded to the database.  There is no current plan to include this in Boxtech but welcome you to provide a user story for BIC to consider its benefit, would like to understand how this could be useful ?

Look forward to hearing back, happy to discuss by other means if preferred

Best Regards 

David

**Comment by rlilov** [comment]
Hi @cmsdroff ,
Containers over their average lifetime (10-15 years) undergo various forms of repairs and refurbishments (including heavy tested upgrades), change of floor, change of doors, natural wetting of floor etc. All this impacts both container tare and its max payload.
I am not sure how often you get updates from carriers when this happens, but by not providing last updated date of the container specification via boxtech channel, you are basically taking on a responsibility that is a bit too much, imo. 

Best is to say via your API: container xxxx has a tare xxxx and payload xxxx as of 21.Feb.2018 as per our files.
Experienced API consumer then would probably initiate check of this data (via offline or direct carrier channels) before accepting it, as chances for this data to be incorrect are (very) high.

**Comment by oldskeptic** [comment]
+1 on this. This is a help in dealing with contradictory and out of date data.

**Comment by cmsdroff** [comment]
Hi @rlilov 

We discussed this recently and there's a couple of points that came up from this.  The first is that the nature of how and when container owners upload varies, some replace the full fleet file each and every time, others upload as and when change takes place (like a rss feed of container data), so adding a date will only show when the container was uploaded/last uploaded to Boxtech.

Also from the discussion there are the practicalities of updates to the fleet when containers are repaired, some have arrangements in place to apply fixes to containers 'as needed' under a maintenance arrangement with their partners to reduce the administrative burden, others use a quote/fix approach for every repair.  There is no guarantee that for every repair that the container owner knows about OR updates the record in their own dataset (we simply do not know) if the container is remarked with new weights for example this should trigger an update to the container owner which will find its way into Boxtech for integrated container owners.

I think it will make sense to include the updated date for the record but i'm not fully convinced it will answer with certainty what you are looking to achieve from above, but maybe it will help towards that, thanks for sharing your use case above much appreciated
