### ISSUE TITLE
General Question on data coverage

### ISSUE THREAD

**Issue by acheloos-m** [bic-boxtech/bic-boxtech.github.io#43]
Hello,

we're currently implementing box tech inside a container tracking solution. 
One key part we're interested in is the containers age, given by the manufacturing date.

The Boxtech api spec defines this field, however all containers we tried so far (primarily MSC / SEACO) retured a null value.

Could you give us a hint, how the current coverage of data is inside the Boxtech DB? This would help us to understand if the missing values a just a result of our subset of containers or if the carriers generally do not provide this data.

Also, is there another API for CSC Plate Info?

Best regards &
keep up the good work!

**Comment by cmsdroff** [comment]
Hi @acheloos-m 

Thanks for the question!  

The `manufactured date` is currently optional to the container owner for uploading, hence the missing information that you are looking for.  Our mandatory data is essentially the container door information (container no, iso size type, tare, payload, max gross weight) so its down the owners to provide, the overall uptake of this field is really mixed between container owners.

We are working with container owners to capture the data at manufacture stage to improve the data so there will be improvement here but of course its not guaranteed all container owners will provide or share this data.

For the CSC Plate info, you will see in our API specs we are looking at this https://app.swaggerhub.com/apis/BIC-ORG/Boxtech/2.0.2-postContainer#/combined_data_plate as it would be natural to provide via Boxtech to those who need it, If you can share a little about your use case we can see how it fits with Boxtech and communicate to the owners why this information is useful to encourage them to provide it.

Hope this helps

**Comment by rlilov** [comment]
Hi @acheloos-m ,
If you need this level of details, your best bet is querying the leasing companies.
Example from Textainer 
https://tex.textainer.com/Equipment/StatusAndSpecificationsInquiry.aspx
container number: TEXU2427639
Those are the only sources of information you can get this data from. I am pretty sure it has to be done leasing co by leasing co and chances for an API are close to zero.
HTH
