### ISSUE TITLE
Cannot get JSON output

### ISSUE THREAD

**Issue by kenlane-af** [bic-boxtech/bic-boxtech.github.io#47]
I am able to retrieve my auth token and submit a curl GET for a BIC Code, but the API returns some <!doctype html> data and I cannot see the JSON output described in the documentation.

I've tried with both curl and Postman and tried tweaking the "Accept" parameters. I notice an error from Cloudflare but I am sure it is something more simple than that. Here is the erbose curl output:

kenneths-mbp:~ kennylane$ curl -v --location 'https://api.bic-boxtech.org/api/v2.0/codes/MNBU' --header 'Authorization: <big hash here>'
*   Trying 104.26.6.83:443...
* Connected to api.bic-boxtech.org (104.26.6.83) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=bic-boxtech.org
*  start date: Mar 10 21:02:47 2024 GMT
*  expire date: Jun  8 21:02:46 2024 GMT
*  subjectAltName: host "api.bic-boxtech.org" matched cert's "*.bic-boxtech.org"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://api.bic-boxtech.org/api/v2.0/codes/MNBU
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: api.bic-boxtech.org]
* [HTTP/2] [1] [:path: /api/v2.0/codes/MNBU]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [authorization: <big hash here>
> GET /api/v2.0/codes/MNBU HTTP/2
> Host: api.bic-boxtech.org
> User-Agent: curl/8.4.0
> Accept: */*
> Authorization: <big hash here>
>
< HTTP/2 200
< date: Tue, 30 Apr 2024 15:21:46 GMT
< content-type: text/html
< last-modified: Thu, 25 Apr 2024 13:56:50 GMT
< x-amz-server-side-encryption: AES256
< vary: Accept-Encoding
< x-cache: Error from cloudfront
< via: 1.1 d1dad7d3c339d87d553c26a84c9ca5d2.cloudfront.net (CloudFront)
< x-amz-cf-pop: IAD55-P4
< x-amz-cf-id: VQDfwgAOj4ffjTQlqWrTnQRZ5nlZcHvqjo5VWnJ15nI9zGi7SPHFyg==
< age: 229
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=<big hash here>"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 87c885fdcf8482e1-IAD
<
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>BIC Boxtech | Global Container Database</title>
<base href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta itemprop="name" content="BIC Boxtech | Global Container Database">
<meta itemprop="description" content="BoxTech allows shippers, carriers, terminals, depots, and other supply chain participants to instantly obtain technical information about containers, such as tare weight, size/type and maximum gross mass.">
<meta itemprop="image" content="https://boxtech.cif-consulting.co.uk/assets/img/social-tile.png">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="BIC Boxtech | Global Container Database">
<meta name="twitter:description" content="BoxTech allows shippers, carriers, terminals, depots, and other supply chain participants to instantly obtain technical information about containers, such as tare weight, size/type and maximum gross mass.">
<meta name="twitter:image" content="https://boxtech.cif-consulting.co.uk/assets/img/social-tile.png">

<meta property="og:title" content="BIC Boxtech | Global Container Database" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://www.bic-boxtech.org/" />
<meta property="og:image" content="https://boxtech.cif-consulting.co.uk/assets/img/social-tile.png" />
<meta property="og:description" content="BoxTech allows shippers, carriers, terminals, depots, and other supply chain participants to instantly obtain technical information about containers, such as tare weight, size/type and maximum gross mass." />
<meta property="og:site_name" content="BIC Boxtech | Global Container Database" />

<link rel="icon" type="image/x-icon" href="/assets/favicon/favicon.ico">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">

<link rel="manifest" href="/assets/favicon/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#1B9F88">
<link rel="stylesheet" href="styles.f70258dd77dfb59ffed3.css"></head>
<body>
<app-root></app-root>

<script>
  var global = global || window;
</script>
<script src="runtime.0e49e2b53282f40c8925.js" defer></script><script src="polyfills.1718efd41ef073f31ae1.js" defer></script><script src="main.4fe9904d6bc977e35936.js" defer></script></body>
</html>
* Connection #0 to host api.bic-boxtech.org left intact

**Comment by cmsdroff** [comment]
Hi @kenlane-af 

Thanks for raising, I think this should help:

1. Authenticate using endpoint 

```
curl --location --request POST 'https://app.bic-boxtech.org/api/v2.0/oauth/token' \
--header 'Accept: application/json' \
--header 'Authorization: Basic ZGF2aWRAY...'
```

if your using postman then in the 'Auth' tab set the auth type to `Basic Auth` and enter your Boxtech Username and Password in the boxes provided, otherwise you will need to base64 encode separating the username and password with a `:`, the output will look like above, just make sure the full authorisation is provided in place of `ZGF2aWRAY...`

3. Call the BIC Code Endpoint

```
curl --location 'https://app.bic-boxtech.org/api/v2.0/codes/MNBU' \
--header 'Accept: application/json' \
--header 'Authorization: eyJraWQiOiJUVW9vRTd...'
```

make sure you put the full token returned from the auth endpoint in the above code to replace `eyJraWQiOiJUVW9vRTd...` 

you will get a response as below 

```
[
    {
        "code": "MNBU",
        "name": "MAERSK A/S",
        "address": {
            "country": "Denmark"
        }
    }
]
```

**Comment by ceciliamarquesb** [comment]
I have the same problem. I can get the token from authenticate endpoint, apply it on the authorization header on BIC Code endpoint and the result is a <!doctype html>


![BIC](https://github.com/bic-org/Boxtech/assets/102254983/a797deee-7417-4e50-8aba-9fcf5540a2df)


This happens even if I do in the website 


![BIC2](https://github.com/bic-org/Boxtech/assets/102254983/67c80108-0ede-4bd8-837a-e83632e8aeaa)

**Comment by tvanhove** [comment]
We are having the same issue as @ceciliamarquesb

**Comment by cmsdroff** [comment]
The swagger and API are returning successfully, so we will look into your accounts to see if some permissions have not been set, 

Could you please login to https://portal.bic-code.org using your credentials and ensure you have accepted the terms and conditions for the `BoTech` api please? the `T&C's` button should be green not red like below.

![Screenshot 2024-06-07 at 08 46 07](https://github.com/bic-org/Boxtech/assets/2013960/820841bb-19cd-4a6c-a5f7-ff72190ac718)

Here's the swagger response showing results.

![Screenshot 2024-06-07 at 08 43 19](https://github.com/bic-org/Boxtech/assets/2013960/bcbf2b77-4785-4710-842b-b15857b71d75)

@declanoconnor can you check over this also please?

**Comment by tvanhove** [comment]
@cmsdroff well that did it! Thank you for the quick reply! 

Would it be possible to give some response on the API that gives an indication if the T&C have not been accepted?

**Comment by declanoconnor** [comment]
> @cmsdroff well that did it! Thank you for the quick reply!
> 
> Would it be possible to give some response on the API that gives an indication if the T&C have not been accepted?

Thanks for the feedback @tvanhove 

The API should now return an appropriate response & other permission errors should now be clearer.

**Comment by ceciliamarquesb** [comment]
> The swagger and API are returning successfully, so we will look into your accounts to see if some permissions have not been set,
> 
> Could you please login to https://portal.bic-code.org using your credentials and ensure you have accepted the terms and conditions for the `BoTech` api please? the `T&C's` button should be green not red like below.
> 
> ![Screenshot 2024-06-07 at 08 46 07](https://private-user-images.githubusercontent.com/2013960/337572215-820841bb-19cd-4a6c-a5f7-ff72190ac718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjEwMjUsIm5iZiI6MTcxNzc2MDcyNSwicGF0aCI6Ii8yMDEzOTYwLzMzNzU3MjIxNS04MjA4NDFiYi0xOWNkLTRhNmMtYTVmNy1mZjcyMTkwYWM3MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTE0NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JlYzczODU1NTM2YmY4M2QyZGJjNDc4MmQyMTgyNjViYWJhMDE4NTE5NGJhMGI4NTE0MzQ3MDhlZTMwZmQ1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.27yyWbDq4PPsWEOUSwKs7zJVue6CpI3615QICBK6tUY)
> 
> Here's the swagger response showing results.
> 
> ![Screenshot 2024-06-07 at 08 43 19](https://private-user-images.githubusercontent.com/2013960/337572313-bcbf2b77-4785-4710-842b-b15857b71d75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjEwMjUsIm5iZiI6MTcxNzc2MDcyNSwicGF0aCI6Ii8yMDEzOTYwLzMzNzU3MjMxMy1iY2JmMmI3Ny00Nzg1LTQ3MTAtODQyYi1iMTU4NTdiNzFkNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTE0NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI2MTAzNWJjMDBjYjdhY2JiYWE1OTQwNjZhZTU4YmRiMzVjNTQ3YjM2MmEzNDEwZjY0NWYzOGU4YTAyZTZkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PaRRWEVGyCjUvuNAYpqyTXHJyVP1Lv32p9g6yNI2zhc)
> 
> @declanoconnor can you check over this also please?

Thank you @cmsdroff

Issue solved!
